### PR TITLE
chore: Update quarto-extensions.csv

### PR DESCRIPTION
**Pull request by coatless**

### CODE REVIEW

**Review by mcanouil — APPROVED** [review]

**Comment by mcanouil** [comment]
Thanks!

Note that if you don't have de topics and description to your GutHub repositories, none will be available in the listing.

image

**Comment by coatless** [comment]
@mcanouil updated. I'll take care a few other things on that repo today/tomorrow; wanted to avoid a second PR.

**Comment by mcanouil** [comment]
FYI, I added a check for topics/description.

**Comment by coatless** [comment]
@mcanouil excellent; thanks!

**Pull request merged**
