### PR TITLE
chore: add edvinsyk/quarto-landscape extension

### PR DESCRIPTION
**Pull request by edvinsyk**

### CODE REVIEW

**Comment by mcanouil** [comment]
@edvinsyk Would you mind adding a description to your GitHub repository and possibly topics?
image

**Review by mcanouil — CHANGES_REQUESTED** [review]
@edvinsyk Would you mind adding a description to your GitHub repository and possibly topics?
image

**Comment by edvinsyk** [comment]
Should be done now!

**Review by mcanouil — APPROVED** [review]
Thanks!

**Pull request merged**
